ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "twoFactorCodeHash" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "twoFactorCodeExpiresAt" TIMESTAMP(3);
